---
- name: Parse and load secrets
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Run secret-loading pre-requisites"
      ansible.builtin.include_role:
        name: '{{ item }}'
      loop:
        - cluster_pre_check
        - find_vp_secrets

    # find_vp_secrets will return a plaintext data structure called values_secrets_data
    # This will allow us to determine schema version and which backend to use
    - name: Determine how to load secrets
      ansible.builtin.set_fact:
        secrets_yaml: '{{ values_secrets_data | from_yaml }}'

    - name: Load secrets using Kubernetes
      ansible.builtin.include_role:
        name: k8s_secret_utils
      when:
        - secrets_yaml['backingStore'] is defined
        - secrets_yaml['version'] is defined
        - secrets_yaml['version'] >= '3.0'
        - secrets_yaml['backingStore'] == 'kubernetes'

    - name: Load secrets into Vault
      ansible.builtin.include_role:
        name: vault_utils
      when:
        - secrets_yaml['backingStore'] | default('vault') == 'vault'
