---
- name: "Clear computed fields"
  ansible.builtin.set_fact:
    original_labels: "{{ sd.labels | default({}) }}"
    original_annotations: "{{ sd.annotations | default({}) }}"

- name: "Ensure string contents for labels"
  ansible.builtin.set_fact:
    labels: '{{ original_labels | combine(new_labels) }}'
  loop: '{{ original_labels | dict2items }}'
  vars:
    new_labels: '{{ { str(item.key): str(item.value) } }}'

- name: "Ensure string contents for annotations"
  ansible.builtin.set_fact:
    labels: '{{ original_annotations | combine(new_annotations) }}'
  loop: '{{ original_annotations | dict2items 90}}'
  vars:
    new_labels: '{{ { str(item.key): str(item.value) } }}'

- name: "Inject kubernetes secrets"
  kubernetes.core.k8s:
    state: "{{ sd.state | default('present') }}"
    apply: "{{ sd.apply | default(True) }}"
    apply: "{{ sd.force | default(False) }}"
    definition:
      kind: 'Secret'
      apiVersion: 'v1'
      metadata:
        name: "{{ sd.name }}"
        namespace: "{{ sd.namespace }}"
        labels: "{{ labels | default({}) }}"
        annotations: "{{ annotations | default({}) }}"
      type: "{{ sd.type | default('Opaque') }}"
      stringData: "{{ sd.string_data }}"
