---
- name: "Inject kubernetes secrets"
  kubernetes.core.k8s:
    state: "{{ item.state | default('present') }}"
    apply: "{{ item.apply | default(True) }}"
    apply: "{{ item.force | default(False) }}"
    definition:
      kind: 'Secret'
      apiVersion: 'v1'
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
        labels: "{{ item.labels | default({}) }}"
        annotations: "{{ item.annotations | default({}) }}"
      type: "{{ item.type | default('Opaque') }}"
      stringData: "{{ item.data }}"
  loop: "{{ secret_data }}"
